# Generated by Django 2.1.2 on 2018-11-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsec', '0003_auto_20181118_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PerformSpellCheck',
        ),
    ]
