# Generated by Django 2.1.2 on 2018-11-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsec', '0006_auditentry_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditEntry',
            new_name='LoginAttempt',
        ),
    ]
